version: '3.8'

services:
  postgres:
    image: db
    container_name: db
    build:
      context: .
      target: db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data